export const SET_FILTERS_VALUE = 'SET_FILTERS_VALUE';
export const SET_LANGUAGE = 'SET_LANGUAGE';

export const REQUEST_USER_FORMS = 'REQUEST_USER_FORMS';
export const SET_USER_FORMS = 'SET_USER_FORMS';
export const USER_FORMS_ERROR = 'USER_FORMS_ERROR';

// export const DATA_SET_REQUEST = "DATA_SET_REQUEST";
// export const DATA_SET_SUCCESS = "DATA_SET_SUCCESS";
// export const DATA_SET_ERROR = "DATA_SET_ERROR";

export const SUBMISSIONS_DEQUEUING_START = 'SUBMISSIONS_DEQUEUING_START';
export const SUBMISSIONS_DEQUEUING_FINISH = 'SUBMISSIONS_DEQUEUING_FINISH';

export const IS_APPROVER_FLOW = 'IS_APPROVER_FLOW';
export const IS_USER_FLOW = 'IS_USER_FLOW';
